header: {stamp: {sec: 0, nanosec: 0}, frame_id: ""}
joint_names: ['joint_1_s', 'joint_2_l', 'joint_3_u', 'joint_4_r', 'joint_5_b', 'joint_6_t']
points:
  - positions: [0.0, 0.0, 1.57, 0.0, 0.0, 0.785]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 0
      nanosec: 0
  - positions: [-1.2212777137756348, -0.09789979457855225, 1.4795870780944824, 0.0, -1.577467918395996, 2.006679058074951]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 8
      nanosec: 0
  - positions: [-0.5495364665985107, 0.5194752216339111, 2.2760138511657715, 0.0, -1.7565017938613892, 1.3349438905715942]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 14
      nanosec: 0
  - positions: [-0.32666805386543274, 0.43341436982154846, 2.134032964706421, 0.0, -1.7005678415298462, 1.1120706796646118]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 20
      nanosec: 0
  - positions: [-0.32666805386543274, 0.43341436982154846, 2.134032964706421, 0.0, -1.7005678415298462, 1.1120706796646118]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 24
      nanosec: 0
  - positions: [-0.8596156239509583, -0.33025500178337097, 1.316274881362915, 0.0, -1.646477222442627, 1.6450220346450806]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 32
      nanosec: 0
  - positions: [-0.2160734236240387, -0.33024194836616516, 1.3163120746612549, 0.0, -1.6464879512786865, 1.0014854669570923]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 41
      nanosec: 0
  - positions: [-0.07795264571905136, 0.43341436982154846, 2.1340553760528564, 0.0, -1.7005894184112549, 0.863359272480011]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 51
      nanosec: 0
  - positions: [0.07852107286453247, 0.4769544303417206, 2.2046666145324707, 0.0, -1.7276670932769775, 0.7068865895271301]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 59
      nanosec: 0
  - positions: [0.39363768696784973, -0.15463124215602875, 1.4329019784927368, 0.0, -1.5875035524368286, 0.3917637765407562]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 69
      nanosec: 0
  - positions: [0.0, 0.0, 1.57, 0.0, 0.0, 0.785]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 76
      nanosec: 0
